import * as core from "./schema/core.js";

/**
 * Registre de classification des données (v0, section 3.2). Chaque colonne de la base core porte ici sa
 * catégorie ; le test `classification.test.ts` échoue si une colonne est ajoutée sans être classée, ou si une
 * entrée du registre ne correspond plus à aucune colonne.
 *
 * Le v0 demande que chaque colonne porte sa classification. Un commentaire de migration ne se vérifie pas :
 * ce registre, lui, est exécutable, et c'est ce qui empêche l'oubli au moment d'ajouter une table.
 *
 * PUBLIC              diffusable au palier T0, y compris à un visiteur non connecté.
 * INTERNAL            interne à la plateforme : identifiants, états, horodatages d'exploitation.
 * PERSONAL            se rapporte à une personne identifiable : nom, email, téléphone, appareil.
 * SENSITIVE_PERSONAL  compromet un compte si elle fuit : empreintes de mot de passe, de jeton, de code.
 * CONFIDENTIAL_DEAL   contenu d'une transaction : prix, conditions, pièces, échanges. Chiffré au repos
 *                     quand la colonne porte le suffixe _enc, protégé par palier dans tous les cas.
 */
export type DataClass = "PUBLIC" | "INTERNAL" | "PERSONAL" | "SENSITIVE_PERSONAL" | "CONFIDENTIAL_DEAL";

export const CLASSIFICATION: Record<string, Record<string, DataClass>> = {
  dealConversations: { id: "INTERNAL", dealId: "INTERNAL", sellerOrganisationId: "INTERNAL", investorOrganisationId: "INTERNAL", createdAt: "INTERNAL" },
  organisations: {
    id: "INTERNAL",
    name: "INTERNAL",
    attributionChannel: "INTERNAL",
    attributionCampaignId: "INTERNAL",
    attributionReferralCode: "INTERNAL",
    cciMemberConfirmationRef: "INTERNAL",
    attributionCapturedAt: "INTERNAL",
    createdAt: "INTERNAL",
  },
  persons: {
    id: "INTERNAL",
    legalName: "PERSONAL",
    relatedPersonGroupId: "INTERNAL",
    createdAt: "INTERNAL",
  },
  users: {
    id: "INTERNAL",
    organisationId: "INTERNAL",
    personId: "INTERNAL",
    email: "PERSONAL",
    emailVerifiedAt: "PERSONAL",
    phoneE164: "PERSONAL",
    phoneVerifiedAt: "PERSONAL",
    passwordHash: "SENSITIVE_PERSONAL",
    roles: "INTERNAL",
    consentTermsAt: "INTERNAL",
    consentPrivacyAt: "INTERNAL",
    consentMarketingAt: "INTERNAL",
    createdAt: "INTERNAL",
  },
  sessions: {
    id: "INTERNAL",
    userId: "INTERNAL",
    tokenHash: "SENSITIVE_PERSONAL",
    deviceLabel: "PERSONAL",
    ipHash: "PERSONAL",
    expiresAt: "INTERNAL",
    revokedAt: "INTERNAL",
    lastSeenAt: "INTERNAL",
    createdAt: "INTERNAL",
  },
  otpChallenges: {
    id: "INTERNAL",
    userId: "INTERNAL",
    purpose: "INTERNAL",
    codeHash: "SENSITIVE_PERSONAL",
    attempts: "INTERNAL",
    expiresAt: "INTERNAL",
    consumedAt: "INTERNAL",
    createdAt: "INTERNAL",
  },
  subscriptions: {
    id: "INTERNAL",
    organisationId: "INTERNAL",
    tier: "INTERNAL",
    entitlementsVersion: "INTERNAL",
    periodStart: "INTERNAL",
    periodEnd: "INTERNAL",
    paymentState: "INTERNAL",
    createdAt: "INTERNAL",
  },
  companies: {
    id: "INTERNAL",
    ownerOrganisationId: "INTERNAL",
    legalName: "INTERNAL",
    legalForm: "INTERNAL",
    rccmNumber: "INTERNAL",
    registryRecordId: "INTERNAL",
    createdAt: "INTERNAL",
  },
  registryRecords: {
    id: "INTERNAL",
    companyId: "INTERNAL",
    rccmNumber: "INTERNAL",
    legalName: "INTERNAL",
    legalForm: "INTERNAL",
    registrationDate: "INTERNAL",
    status: "INTERNAL",
    registeredAddress: "INTERNAL",
    officers: "INTERNAL",
    verifiedAt: "INTERNAL",
    verifiedBy: "INTERNAL",
    sourceRef: "INTERNAL",
    mode: "INTERNAL",
  },
  registryConsultations: {
    id: "INTERNAL", companyId: "INTERNAL", requestId: "INTERNAL", requestHash: "INTERNAL",
    officerUserId: "INTERNAL", rccmNumber: "INTERNAL", declaredIdentity: "INTERNAL", mode: "INTERNAL",
    provider: "INTERNAL", synthetic: "INTERNAL", outcome: "INTERNAL", result: "INTERNAL", reason: "INTERNAL",
    fallbackFromId: "INTERNAL", registryRecordId: "INTERNAL", createdAt: "INTERNAL",
  },
  membershipConfirmations: {
    id: "INTERNAL",
    organisationId: "INTERNAL",
    confirmationRef: "INTERNAL",
    confirmedBy: "INTERNAL",
    confirmedAt: "INTERNAL",
  },
  deals: {
    id: "INTERNAL",
    companyId: "INTERNAL",
    sellerOrganisationId: "INTERNAL",
    dealType: "INTERNAL",
    status: "INTERNAL",
    visibility: "INTERNAL",
    sectorCode: "PUBLIC",
    regionCode: "PUBLIC",
    turnoverBand: "PUBLIC",
    askingPriceEnc: "CONFIDENTIAL_DEAL",
    valuationBasisEnc: "CONFIDENTIAL_DEAL",
    disclosureCount: "INTERNAL",
    circleCap: "INTERNAL",
    createdAt: "INTERNAL",
  },
  assetDealDetails: {
    dealId: "INTERNAL",
    assetsDescription: "CONFIDENTIAL_DEAL",
    includesGoodwill: "INTERNAL",
  },
  shareDealDetails: {
    dealId: "INTERNAL",
    legalForm: "INTERNAL",
    apeEligible: "INTERNAL",
    securityType: "CONFIDENTIAL_DEAL",
    stakePercentEnc: "CONFIDENTIAL_DEAL",
    transferRestrictionsEnc: "CONFIDENTIAL_DEAL",
  },
  dealEvents: {
    id: "INTERNAL",
    dealId: "INTERNAL",
    fromStatus: "INTERNAL",
    toStatus: "INTERNAL",
    actorUserId: "INTERNAL",
    reason: "INTERNAL",
    occurredAt: "INTERNAL",
  },
  interests: {
    id: "INTERNAL",
    dealId: "INTERNAL",
    investorUserId: "INTERNAL",
    message: "INTERNAL",
    matchReasons: "INTERNAL",
    createdAt: "INTERNAL",
  },
  certifications: {
    id: "INTERNAL",
    companyId: "INTERNAL",
    scopeStatement: "PUBLIC",
    decision: "PUBLIC",
    officerUserId: "INTERNAL",
    decidedAt: "PUBLIC",
    expiresAt: "PUBLIC",
    revocationReason: "INTERNAL",
    registryInvalidatedAt: "INTERNAL",
  },
  indicativeValuations: {
    id: "INTERNAL",
    dealId: "INTERNAL",
    method: "INTERNAL",
    equityLowEnc: "CONFIDENTIAL_DEAL",
    equityHighEnc: "CONFIDENTIAL_DEAL",
    calculationLog: "INTERNAL",
    sources: "INTERNAL",
    computedBy: "INTERNAL",
    computedAt: "INTERNAL",
  },
  feeEvents: {
    id: "INTERNAL",
    dealId: "INTERNAL",
    basisXof: "INTERNAL",
    tierRatePercent: "INTERNAL",
    minimumApplied: "INTERNAL",
    platformShareXof: "INTERNAL",
    institutionShareXof: "INTERNAL",
    status: "INTERNAL",
    createdAt: "INTERNAL",
  },
  auditEvents: {
    id: "INTERNAL",
    action: "INTERNAL",
    actorUserId: "INTERNAL",
    subjectType: "INTERNAL",
    subjectId: "INTERNAL",
    outcome: "INTERNAL",
    correlationId: "INTERNAL",
    metadata: "INTERNAL",
    occurredAt: "INTERNAL",
  },
  events: {
    id: "INTERNAL",
    title: "PUBLIC",
    description: "PUBLIC",
    startsAt: "PUBLIC",
    endsAt: "PUBLIC",
    capacity: "PUBLIC",
    integrationMode: "INTERNAL",
    remoEventId: "INTERNAL",
    organiserUserId: "INTERNAL",
    campaignId: "INTERNAL",
    status: "INTERNAL",
    createdAt: "INTERNAL",
  },
  eventRegistrations: {
    id: "INTERNAL",
    eventId: "INTERNAL",
    userId: "INTERNAL",
    displayName: "PERSONAL",
    consentContactAt: "INTERNAL",
    ticketRef: "INTERNAL",
    joinedAt: "INTERNAL",
    createdAt: "INTERNAL",
  },
  diasporaAppointments: {
    id: "INTERNAL",
    investorUserId: "INTERNAL",
    dealId: "INTERNAL",
    requestedSlot: "INTERNAL",
    status: "INTERNAL",
    remoEventId: "INTERNAL",
    confirmedBy: "INTERNAL",
    crossBorderNoticeShownAt: "INTERNAL",
    createdAt: "INTERNAL",
  },
  idempotencyKeys: {
    requestHash: "INTERNAL",
    key: "INTERNAL",
    responseStatus: "INTERNAL",
    responseBody: "INTERNAL",
    createdAt: "INTERNAL",
  },
  dealDocuments: {
    id: "INTERNAL",
    dealId: "INTERNAL",
    category: "INTERNAL",
    title: "INTERNAL",
    fileName: "INTERNAL",
    contentType: "INTERNAL",
    sizeBytes: "INTERNAL",
    sha256: "INTERNAL",
    storageKey: "CONFIDENTIAL_DEAL",
    storageVersionId: "INTERNAL",
    version: "INTERNAL",
    supersedesId: "INTERNAL",
    supersededAt: "INTERNAL",
    scanState: "INTERNAL",
    scanEngine: "INTERNAL",
    scanSignature: "INTERNAL",
    uploadedBy: "INTERNAL",
    uploadedAt: "INTERNAL",
  },
  declaredFacts: {
    id: "INTERNAL",
    dealId: "INTERNAL",
    fieldKey: "INTERNAL",
    periodLabel: "INTERNAL",
    valueText: "INTERNAL",
    valueAmountXof: "INTERNAL",
    source: "INTERNAL",
    sourceDocumentId: "INTERNAL",
    note: "CONFIDENTIAL_DEAL",
    version: "INTERNAL",
    supersedesId: "INTERNAL",
    supersededAt: "INTERNAL",
    declaredBy: "INTERNAL",
    declaredAt: "INTERNAL",
  },
  certificationRequests: {
    id: "INTERNAL",
    companyId: "INTERNAL",
    state: "INTERNAL",
    message: "INTERNAL",
    remediationItems: "INTERNAL",
    remediationSetBy: "INTERNAL",
    remediationSetAt: "INTERNAL",
    certificationId: "INTERNAL",
    requestedBy: "INTERNAL",
    requestedAt: "INTERNAL",
    closedAt: "INTERNAL",
  },
  dealViews: {
    id: "INTERNAL",
    dealId: "INTERNAL",
    viewerUserId: "INTERNAL",
    viewerOrganisationId: "INTERNAL",
    viewedAt: "INTERNAL",
  },
  dealMessages: {
    conversationId: "INTERNAL",
    id: "INTERNAL",
    dealId: "INTERNAL",
    interestId: "INTERNAL",
    senderUserId: "INTERNAL",
    senderOrganisationId: "INTERNAL",
    body: "INTERNAL",
    createdAt: "INTERNAL",
  },
  savedAlerts: {
    id: "INTERNAL",
    userId: "INTERNAL",
    organisationId: "INTERNAL",
    label: "INTERNAL",
    sectorCode: "INTERNAL",
    regionCode: "INTERNAL",
    turnoverBand: "INTERNAL",
    dealReadyOnly: "INTERNAL",
    notifyOptIn: "INTERNAL",
    optInAt: "INTERNAL",
    revokedAt: "INTERNAL",
    createdAt: "INTERNAL",
  },
  notificationIntents: {
    id: "INTERNAL", alertId: "INTERNAL", dealId: "INTERNAL", userId: "INTERNAL", organisationId: "INTERNAL",
    score: "INTERNAL", reasons: "INTERNAL", state: "INTERNAL", attempts: "INTERNAL", nextAttemptAt: "INTERNAL",
    leaseUntil: "INTERNAL", expiresAt: "INTERNAL", providerRef: "INTERNAL", lastError: "INTERNAL", createdAt: "INTERNAL", updatedAt: "INTERNAL",
  },
};

/** Colonnes chiffrées au repos : le registre et le schéma doivent rester d'accord (suffixe _enc). */
export const ENCRYPTED_SUFFIX = "Enc";

export function classOf(table: string, column: string): DataClass | undefined {
  return CLASSIFICATION[table]?.[column];
}

/** Tables du schéma core, pour parcourir le registre depuis les tests. */
export const CORE_TABLES = core;
