
const F=window.SCENARIO_FIXTURE; let tab='overview'; let events=[]; let state=F.state_in;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function log(type,detail={}){events.unshift({ts:new Date().toISOString(),type,detail});renderLog();}
function renderLog(){const h=$('#eventlog');if(!h)return;h.innerHTML=events.map(e=>`<div class="event"><b>${esc(e.type)}</b> · ${esc(e.ts.slice(11,19))}<br>${esc(JSON.stringify(e.detail))}</div>`).join('')||'<div class="event">Aucun événement simulé.</div>'}
function kv(k,v){return `<div class="kv"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`}
function noticeClass(){return F.archetype==='CONTROL_FAILURE'?'danger':F.archetype==='REMEDIATION'?'warn':'success'}
function render(){document.body.innerHTML=`<div class="topnote">SPÉCIMEN SYNTHÉTIQUE · DONNÉES FICTIVES · RÉFÉRENCE PRODUIT / QA</div><div class="header"><img class="logo" src="./assets/dealpme-logo.jpg"><div class="headtitle">Référence interactive · ${esc(F.service_label)}</div><select id="profile" class="profile" data-control-id="PROFILE_SWITCH">${F.test_profiles.map(p=>`<option>${esc(p)}</option>`).join('')}</select></div><section class="hero"><div class="hero-in"><div><span class="badge">${esc(F.service_label)}</span><span class="badge alt">${esc(F.archetype)}</span><span class="badge alt">${esc(F.capability_status)}</span><h1>${esc(F.title)}</h1><p>${esc(F.objective)}</p></div><div class="hero-card"><strong>État attendu · ${esc(F.state_out)}</strong><small>${esc(F.expected_user_message)}</small><div class="actions"><button class="btn primary" data-control-id="PRIMARY_ACTION">${esc(F.primary_action.label)}</button><button class="btn" data-control-id="SECONDARY_ACTION">${esc(F.secondary_action.label)}</button></div></div></div></section><div class="tabs">${[['overview','Situation'],['workflow','Parcours'],['controls','Contrôles & RACI'],['evidence','Preuves & audit'],['tests','Tests dev']].map(([id,l])=>`<button class="tab ${tab===id?'active':''}" data-tab="${id}" data-control-id="TAB_${id.toUpperCase()}">${l}</button>`).join('')}</div><main class="main"><div id="slot"></div></main><div id="modal"></div>`; $$('.tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;log('TAB_CHANGED',{tab});render()}); $('[data-control-id="PRIMARY_ACTION"]').onclick=()=>act('PRIMARY_ACTION'); $('[data-control-id="SECONDARY_ACTION"]').onclick=()=>act('SECONDARY_ACTION'); $('#profile').onchange=e=>{log('PROFILE_CHANGED',{profile:e.target.value});}; renderTab(); renderLog();}
function renderTab(){const s=$('#slot');if(tab==='overview'){s.innerHTML=`<div class="grid two"><section class="card"><h2>Situation de test</h2><div class="notice ${noticeClass()}">${esc(F.expected_user_message)}</div>${kv('Déclencheur',F.trigger)}${kv('État initial',F.state_in)}${kv('État courant simulé',state)}${kv('État cible',F.state_out)}${kv('Capacité',F.capability_status)}</section><aside class="card"><h2>Responsabilité de décision</h2>${kv('Décision humaine requise',F.human_decision.required?'Oui':'Non')}${kv('Propriétaire',F.human_decision.owner)}${kv('Décision',F.human_decision.decision)}<p style="color:var(--text);line-height:1.5">${esc(F.human_decision.evidence)}</p></aside></div><div class="grid two" style="margin-top:16px"><section class="card"><h2>Entrées</h2>${F.inputs.map(x=>`<div class="control"><b>${esc(x.name)}</b><small>${esc(x.status)} · preuve ${esc(x.evidence_status)}</small></div>`).join('')}</section><section class="card"><h2>Dépendances</h2>${F.dependencies.map(x=>`<div class="control"><b>${esc(x.name)}</b><small>${esc(x.status)} · ${x.required?'requise':'optionnelle'}${x.fallback?' · secours : '+esc(x.fallback):''}</small></div>`).join('')}</section></div>`}
if(tab==='workflow'){s.innerHTML=`<section class="card"><h2>Parcours exécutable</h2><div class="flow">${F.events.map(e=>`<div class="step"><div class="seq">${e.seq}</div><div><b>${esc(e.type)}</b><small>${esc(e.result)}</small></div><span class="actor">${esc(e.actor)}</span></div>`).join('')}</div></section><section class="card" style="margin-top:16px"><h2>États interdits</h2>${F.prohibited_states.length?F.prohibited_states.map(x=>`<span class="pill red">${esc(x)}</span>`).join(' '):'<span class="pill green">Aucun au-delà des règles générales</span>'}</section>`}
if(tab==='controls'){s.innerHTML=`<div class="grid two"><section class="card"><h2>Contrôles clés</h2><table class="table"><thead><tr><th>ID</th><th>Règle</th><th>Propriétaire</th><th>Blocage</th></tr></thead><tbody>${F.controls.map(c=>`<tr><td><b>${esc(c.id)}</b></td><td>${esc(c.rule)}</td><td>${esc(c.owner)}</td><td>${c.blocking?'Oui':'Non'}</td></tr>`).join('')}</tbody></table></section><aside class="card"><h2>RACI simplifiée</h2>${F.actors.map(a=>`<div class="control"><b>${esc(a.role)}</b><small>${esc(a.responsibility)}</small></div>`).join('')}</aside></div>`}
if(tab==='evidence'){s.innerHTML=`<div class="grid two"><section class="card"><h2>Preuves attendues</h2>${F.evidence_pack.map(x=>`<div class="control"><b>${esc(x.id)}</b><small>${esc(x.description)} · source ${esc(x.source)}</small></div>`).join('')}</section><aside class="card"><h2>Journal simulé</h2><div id="eventlog" class="eventlog"></div></aside></div>`;renderLog()}
if(tab==='tests'){s.innerHTML=`<div class="grid two"><section class="card"><h2>Assertions de qualité</h2>${F.qa_assertions.map((x,i)=>`<div class="test"><div>QA-${String(i+1).padStart(2,'0')}</div><div>${esc(x)}</div><div class="statuspass">À vérifier</div></div>`).join('')}</section><section class="card"><h2>Assertions négatives</h2>${F.negative_assertions.map((x,i)=>`<div class="test"><div>NEG-${String(i+1).padStart(2,'0')}</div><div>${esc(x)}</div><div class="statusblock">Doit échouer</div></div>`).join('')}</section></div><section class="card" style="margin-top:16px"><h2>Contrats d’interaction</h2><table class="table"><thead><tr><th>Control ID</th><th>Action</th><th>Succès</th><th>Audit</th></tr></thead><tbody>${F.interaction_contracts.map(c=>`<tr><td>${esc(c.control_id)}</td><td>${esc(c.action)}</td><td>${esc(c.success_state)}</td><td>${esc(c.audit_event)}</td></tr>`).join('')}</tbody></table></section>`}}
function act(id){const c=F.interaction_contracts.find(x=>x.control_id===id);if(!c){show('Contrôle non enregistré','Ce contrôle serait un défaut DEAD_CONTROL.');return}log(c.audit_event,{control_id:id,action:c.action}); if(F.archetype==='CONTROL_FAILURE' && id==='PRIMARY_ACTION' && c.blocked_state){state=c.blocked_state;show('Action bloquée comme prévu',c.blocked_message||F.expected_user_message);return}state=c.success_state;show('État simulé',`Action : ${c.label}
Résultat attendu : ${c.success_state}
Événement : ${c.audit_event}`)}
function show(title,msg){$('#modal').innerHTML=`<div class="modalback"><div class="modal"><div class="modalhead"><b>${esc(title)}</b><button class="close" data-control-id="MODAL_CLOSE">×</button></div><div class="modalbody"><div class="notice ${noticeClass()}">${esc(msg).replace(/\n/g,'<br>')}</div><p style="font-size:12px;color:var(--muted)">Cette interaction est un contrat de référence pour le développement. Les contrôles réels doivent être appliqués côté serveur lorsque l’autorisation est concernée.</p></div><div class="modalfoot"><button class="btn" data-control-id="MODAL_CLOSE">Fermer</button></div></div></div>`;$$('[data-control-id="MODAL_CLOSE"]').forEach(b=>b.onclick=()=>{$('#modal').innerHTML='';log('MODAL_CLOSED')})}
render();
