const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const fmt = new Intl.NumberFormat('fr-FR', {maximumFractionDigits:0});
const pct = (v,d=1)=> `${(v*100).toFixed(d).replace('.',',')} %`;
const m = v => `${fmt.format(v)} M FCFA`;
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state = {fixture:null, profile:'AUTHORIZED', tab:'overview', favorite:false, selectedFolder:null, selectedDoc:null, docContent:'', docFilter:'', qaFilter:'ALL', audit:[], contactRequested:false, interestRecorded:false, meetingRequested:false, modal:null};

async function load(){
  let fixture, documents, risks, qa, interaction;
  if(window.__DEALPME_DATA__){
    ({fixture,documents,risks,qa,interaction}=window.__DEALPME_DATA__);
    fixture=structuredClone(fixture); documents=structuredClone(documents); risks=structuredClone(risks); qa=structuredClone(qa); interaction=structuredClone(interaction);
  } else {
    [fixture, documents, risks, qa, interaction] = await Promise.all([
      fetch('./data/pt001.fixture.v3.json').then(r=>r.json()),
      fetch('./data/documents.json').then(r=>r.json()),
      fetch('./data/risks.json').then(r=>r.json()),
      fetch('./data/q-and-a.json').then(r=>r.json()),
      fetch('./data/interaction-contract.json').then(r=>r.json()),
    ]);
  }
  fixture.documents=documents; fixture.risk_register=risks; fixture.qa_threads=qa; fixture.interaction_contracts=interaction.contracts;
  state.fixture=fixture;
  state.selectedFolder=fixture.vdr.folders[0];
  const params=new URLSearchParams(location.search);
  state.profile=params.get('profile')||'AUTHORIZED';
  state.tab=(location.hash||'#overview').slice(1);
  if(!['overview','financials','transaction','risks','documents','qa','vdr'].includes(state.tab)) state.tab='overview';
  renderShell(params.get('dev')==='1' || Boolean(window.__FORCE_DEV__));
  if(state.tab==='vdr') openVdr(true);
}
function profile(){return state.fixture.interaction_profiles[state.profile]||state.fixture.interaction_profiles.AUTHORIZED}
function allowed(required){
  const p=profile();
  if(required==='GUEST') return true;
  if(required==='QUALIFIED') return p.authenticated&&p.qualified&&!p.revoked;
  if(required==='AUTHORIZED') return p.authenticated&&p.qualified&&p.admitted&&p.nda_executed&&p.t2_granted&&p.seller_approved&&!p.revoked;
  return false;
}
function audit(event,details={}){state.audit.push({event,at:new Date().toISOString(),profile:state.profile,...details}); window.__dealpmeAudit=state.audit}
function toast(title,msg,type='success'){const host=$('.toast-host');const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<strong>${esc(title)}</strong><p>${esc(msg)}</p>`;host.append(el);setTimeout(()=>el.remove(),4800)}
function routeTab(tab){
  const gate=tab==='overview'?'GUEST':'AUTHORIZED';
  if(!allowed(gate)){showGate(`TAB_${tab.toUpperCase()}`);return}
  state.tab=tab; location.hash=tab; audit('TAB_VIEWED',{tab}); renderTabs(); renderTab();
}
function vdrGate(){
  const p=profile();
  if(p.revoked) return ['ACCESS_REVOKED','Accès révoqué','Cet accès VDR a été révoqué. Toute URL de document active doit être invalidée dans le délai cible.'];
  if(!p.authenticated) return ['LOGIN_REQUIRED','Connexion requise',`Connectez-vous ou créez un compte. La destination ${state.fixture.case_id} doit être conservée après authentification.`];
  if(!p.qualified) return ['QUALIFICATION_REQUIRED','Qualification requise','Complétez la qualification acquéreur et la capacité d’exécution avant toute admission.'];
  if(!p.admitted) return ['ADMISSION_REQUIRED','Admission au cercle requise','Soumettez une demande d’admission. Pour une cession de titres, l’admission reste une décision humaine.'];
  if(!p.nda_executed) return ['NDA_REQUIRED','Accord de confidentialité requis','Exécutez l’accord de confidentialité admissible avant tout accès détaillé.'];
  if(!p.t2_granted) return ['T2_GRANT_REQUIRED','Accès T2 non accordé','Votre NDA est enregistré, mais l’accès détaillé T2 n’a pas encore été accordé.'];
  if(!p.seller_approved) return ['SELLER_APPROVAL_REQUIRED','Autorisation du cédant requise','Le cédant ou son conseil doit accorder l’accès à la VDR pour ce dossier.'];
  return null;
}
function showGate(control){
  audit('ACCESS_GATE_SHOWN',{control});
  const g=vdrGate() || ['ACCESS_GATE','Accès contrôlé','Votre profil actuel ne permet pas cette action.'];
  state.modal={kind:'gate',code:g[0],title:g[1],message:g[2]}; renderModal();
}
function openVdr(fromRoute=false){
  audit('VDR_OPEN_ATTEMPT');
  const g=vdrGate(); if(g){state.modal={kind:'gate',code:g[0],title:g[1],message:g[2]}; renderModal(); if(fromRoute){state.tab='overview';location.hash='overview'} return;}
  state.tab='vdr'; location.hash='vdr'; audit('VDR_OPENED'); renderVdr();
}
function closeVdr(){state.tab='overview';location.hash='overview';renderShell(new URLSearchParams(location.search).get('dev')==='1' || Boolean(window.__FORCE_DEV__))}
function handleControl(id, payload={}){
  const c=state.fixture.interaction_contracts.find(x=>x.control_id===id); if(!c){toast('Contrôle non référencé',id,'error');return}
  audit(c.audit_event,{control_id:id});
  if(c.required_profile && !allowed(c.required_profile)){showGate(id);return}
  switch(c.action){
    case 'SHOW_TAB': routeTab(c.target);break;
    case 'OPEN_VDR': openVdr();break;
    case 'TOGGLE_FAVORITE': state.favorite=!state.favorite;toast(state.favorite?'Ajouté aux favoris':'Retiré des favoris',state.favorite?`${state.fixture.case_id} est enregistré dans votre sélection.`:`${state.fixture.case_id} a été retiré de votre sélection.`);renderHeader();break;
    case 'REQUEST_CONTACT': state.contactRequested=true;toast('Demande enregistrée','Le contact est simulé : aucun message réel n’est envoyé.');renderHeader();renderTab();break;
    case 'EXPRESS_INTEREST': state.interestRecorded=true;toast('Intérêt enregistré','Manifestation d’intérêt synthétique créée et journalisée.');renderTab();break;
    case 'REQUEST_MEETING': state.meetingRequested=true;toast('Réunion demandée','Demande de réunion management ajoutée au workflow de démonstration.');renderTab();break;
    case 'OPEN_DOCUMENT': openDocument(payload.documentId);break;
    case 'DOWNLOAD_DOCUMENT': attemptDownload(payload.documentId);break;
    case 'ASK_QUESTION': createQuestion();break;
    case 'FILTER': renderTab();break;
    case 'SET_PROFILE': state.profile=payload.profile;toast('Profil de test changé',state.fixture.interaction_profiles[state.profile].label);audit('DEV_PROFILE_CHANGED',{new_profile:state.profile}); if(state.tab==='vdr'){const g=vdrGate(); if(g){closeVdr(); showGate('OPEN_VDR')}} else {renderShell(true)}break;
    case 'NAVIGATE_REFERENCE': routeTab(c.target);break;
    case 'OUT_OF_FIXTURE_SCOPE': state.modal={kind:'scope',title:`Hors périmètre du fixture ${state.fixture.case_id}`,message:`La route cible ${c.target} appartient à la plateforme complète. Le contrôle répond ici par un état explicite plutôt que par un lien mort.`};renderModal();break;
    case 'CLOSE_VDR': closeVdr();break;
    case 'CLOSE_MODAL': state.modal=null;renderModal();break;
    case 'SELECT_FOLDER': state.selectedFolder=payload.folder;renderVdrDocList();break;
    case 'SELECT_DOCUMENT': selectVdrDoc(payload.documentId);break;
    case 'FILTER_INPUT': break;
    case 'FILTER_SELECT': break;
    case 'SUBMIT_QUESTION': submitQuestion();break;
    case 'INPUT_TEXT': break;
  }
}
function renderShell(dev=false){
  document.querySelector('#app').innerHTML=`
    <div class="demo-banner">${esc(state.fixture.ui_copy_contract.synthetic_banner)}</div>
    <div class="devbar ${dev?'visible':''}" data-testid="devbar"><label for="profileSelect">Mode de test · profil d’accès</label><select id="profileSelect" data-control-id="DEV_SET_PROFILE">${Object.entries(state.fixture.interaction_profiles).map(([k,v])=>`<option value="${k}" ${k===state.profile?'selected':''}>${esc(k)} — ${esc(v.label)}</option>`).join('')}</select><span class="dev-status">Fixture v3 · interactions contractuelles activées</span></div>
    <div id="headerSlot"></div><div id="heroSlot"></div><div id="tabsSlot"></div><main class="main"><div id="tabSlot"></div></main><div id="footerSlot"></div>
    <div class="toast-host" aria-live="polite"></div><div id="modalSlot"></div>`;
  renderHeader();renderHero();renderTabs();renderTab();renderFooter();
  if(dev) $('#profileSelect').addEventListener('change',e=>handleControl('DEV_SET_PROFILE',{profile:e.target.value}));
}
function renderHeader(){
  const h=$('#headerSlot'); if(!h)return;
  h.innerHTML=`<header class="header"><img class="logo" src="./assets/dealpme-logo.jpg" alt="DealPME"><nav class="nav"><a class="active" href="#overview" data-control-id="NAV_OPPORTUNITIES">Entreprises à céder</a><a href="javascript:void(0)" data-control-id="NAV_BUYERS">Repreneurs</a><a href="javascript:void(0)" data-control-id="NAV_SERVICES">Services</a><a href="javascript:void(0)" data-control-id="NAV_RESOURCES">Ressources</a><a href="javascript:void(0)" data-control-id="NAV_ABOUT">À propos</a></nav><div class="header-actions"><button class="btn ${state.favorite?'favorite-on':''}" data-control-id="TOGGLE_FAVORITE">${state.favorite?'★ Favori':'☆ Favoris'}</button><button class="btn primary" data-control-id="CONTACT_SELLER">${state.contactRequested?'Demande envoyée':'Contacter le cédant'}</button></div></header>`;
  $$('[data-control-id]',h).forEach(b=>b.addEventListener('click',e=>{e.preventDefault();handleControl(b.dataset.controlId)}));
}
function renderHero(){
  const f=state.fixture, d=f.disclosure.T2.data;
  $('#heroSlot').innerHTML=`<section class="hero"><div class="hero-inner"><button class="back backbtn" data-control-id="BACK_TO_OPPORTUNITIES">← Retour aux opportunités · Réf. ${f.case_id}</button><div class="hero-grid"><div><div class="eyebrow"><span class="badge">DEAL-READY · ${f.deal_ready.preflight_score}/100</span><span class="badge outline">T2 AUTORISÉ · DÉMO</span></div><h1>${esc(d.company)}</h1><div class="hero-sub">${esc(f.master.teaser)}. Toutes les données et pièces ci-dessous sont synthétiques et destinées à la spécification produit.</div><div class="meta"><span>◉ ${esc(f.master.sector)}</span><span>⌖ ${esc(f.master.city)}</span><span>▥ PME</span><span>◷ ${f.master.years} ans d’activité</span></div></div><div class="hero-proof"><strong>Accès détaillé T2 — profil ${esc(state.profile)}</strong><p>${esc(f.master.seller_reason)}</p><div class="proof-line"><span>${m(f.financials.kpis.revenue)} CA 2025</span><span>${m(f.financials.kpis.ebitda)} EBITDA</span></div></div></div></div></section>`;
  $$('[data-control-id]', $('#heroSlot')).forEach(b=>b.addEventListener('click',()=>handleControl(b.dataset.controlId)));
}
function renderTabs(){
  const tabs=[['overview','Aperçu','TAB_OVERVIEW'],['financials','Données financières','TAB_FINANCIALS'],['transaction','Transaction','TAB_TRANSACTION'],['risks','Risques','TAB_RISKS'],['documents','Documents','TAB_DOCUMENTS'],['qa','Q&R','TAB_QA']];
  $('#tabsSlot').innerHTML=`<div class="tabs-wrap"><div class="tabs">${tabs.map(([id,label,c])=>`<button class="tabbtn ${state.tab===id?'active':''}" data-control-id="${c}" data-tab="${id}">${label}</button>`).join('')}</div></div>`;
  $$('.tabbtn').forEach(b=>b.addEventListener('click',()=>handleControl(b.dataset.controlId)));
}
function renderFooter(){
  $('#footerSlot').innerHTML=`<footer class="footer-band"><div class="footer-inner"><div class="footer-copy"><strong>Un parcours sécurisé, progressif et traçable.</strong><small>Fixture ${esc(state.fixture.case_id)} v3 · les contrôles visibles sont reliés à un contrat d’interaction et à des tests.</small></div><div class="stamp">${esc(state.fixture.case_id)} · Reference App 3.0</div><button class="vdr-cta" data-control-id="OPEN_VDR">Ouvrir la VDR →</button></div></footer>`;
  $('[data-control-id="OPEN_VDR"]')?.addEventListener('click',()=>handleControl('OPEN_VDR'));
}
function renderTab(){
  const slot=$('#tabSlot'); if(!slot)return; if(state.tab==='vdr'){openVdr();return}
  const renderers={overview:overview,financials,transaction,risks,documents,qa}; slot.innerHTML=renderers[state.tab](); bindTab();
}
function overview(){const f=state.fixture,k=f.financials.kpis;return `<div class="grid three"><section class="card"><h2>Informations clés</h2>${kv('Chiffre d’affaires 2025',m(k.revenue))}${kv('EBITDA 2025',`${m(k.ebitda)} · ${pct(k.ebitda_margin)}`)}${kv('Effectif',k.headcount)}${kv('Type d’opération','Cession de titres')}${kv('Périmètre',f.master.stake)}${kv('Attente du cédant',m(f.master.asking))}${kv('Accompagnement',f.master.seller_support)}<div class="source-line">${esc(f.ui_copy_contract.asking_disclaimer)}</div></section><section class="card"><h2>Présentation de l’opportunité</h2><p style="line-height:1.65;color:#526079">${esc(f.master.teaser)}. Le fixture relie les données financières, les documents, les risques, les Q&R et le workflow de transaction à une même source canonique.</p><div class="highlights">${f.highlights.map(x=>`<div class="highlight"><span class="icon-dot">✓</span><div><b>${esc(x)}</b><small>Preuve liée dans la VDR</small></div></div>`).join('')}</div><div class="metric-row" style="margin-top:13px"><div class="metric"><small>Précontrôle</small><strong>${f.deal_ready.preflight_score}/100</strong></div><div class="metric"><small>Revenus récurrents</small><strong>${pct(k.recurring_revenue,0)}</strong></div><div class="metric"><small>Top 5 clients</small><strong>${pct(k.top5_customer_concentration,0)}</strong></div><div class="metric"><small>Export</small><strong>${pct(k.export_share,0)}</strong></div></div></section><section class="card"><h2>Niveau d’information</h2><div class="notice"><strong>Accès T2 synthétique</strong><br>Identité, termes et VDR ne sont montrés qu’en mode autorisé. Utilisez <code>?dev=1</code> pour tester les gates.</div><h2 style="margin-top:18px">Transaction</h2>${kv('Motif',f.master.seller_reason)}${kv('Dette brute',m(f.transaction_workspace.gross_debt_mfcfa))}${kv('Trésorerie',m(f.transaction_workspace.cash_mfcfa))}${kv('Dette nette',m(f.transaction_workspace.net_debt_mfcfa))}${kv('Deal-Ready','Certifié — périmètre limité')}</section></div><div class="grid two" style="margin-top:18px"><section class="card"><h2>Trajectoire financière — M FCFA</h2>${barChart()}</section><section class="card"><h2>Risques et VDR</h2><div class="metric-row"><div class="metric"><small>Risques ouverts</small><strong>${f.risk_register.filter(r=>r.status!=='CLOSED').length}</strong></div><div class="metric"><small>Documents</small><strong>${f.documents.length}</strong></div><div class="metric"><small>Q&R</small><strong>${f.qa_threads.length}</strong></div><div class="metric"><small>Dossiers VDR</small><strong>${f.vdr.folder_count}</strong></div></div><div class="divider"></div><div class="notice warning">${esc(f.ui_copy_contract.vdr_protection_copy)}</div></section></div>`}
function financials(){const f=state.fixture,a=f.financials.analysis;return `<div class="section-title"><div><h2>Données financières</h2><p>Vue d’acquisition : compte de résultat, bilan, trésorerie et ratios. ${esc(f.ui_copy_contract.financial_disclaimer)}</p></div><span class="pill green">Source canonique v3</span></div><section class="card">${barChart()}<div class="metric-row" style="margin-top:15px"><div class="metric"><small>CAGR CA 2021–2025</small><strong>${pct(a.revenue_cagr_2021_2025)}</strong></div><div class="metric"><small>CAGR EBITDA</small><strong>${pct(a.ebitda_cagr_2021_2025)}</strong></div><div class="metric"><small>Capex / CA 2025</small><strong>${pct(a.capex_intensity_2025)}</strong></div><div class="metric"><small>CA / salarié</small><strong>${a.revenue_per_employee_2025_mfcfa.toFixed(1).replace('.',',')} M</strong></div></div></section><section class="card" style="margin-top:18px"><h2>Compte de résultat</h2>${incomeTable()}</section><section class="card" style="margin-top:18px"><h2>Bilan et ratios de BFR</h2>${balanceTable()}</section><section class="card" style="margin-top:18px"><h2>Flux de trésorerie</h2>${cashTable()}<div class="source-line">Aucun chiffre n’est présenté comme audité. Le fixture illustre la structure de preuve et les calculs attendus.</div></section>`}
function transaction(){const t=state.fixture.transaction_workspace;return `<div class="section-title"><div><h2>Transaction</h2><p>Mini Deal Workspace : structure, statut, prochaines étapes et actions contrôlées.</p></div><span class="pill amber">Étape actuelle · Audit / VDR</span></div><div class="grid two"><section class="card"><h2>Paramètres de l’opération</h2>${kv('Type','Cession de titres')}${kv('Forme juridique',t.legal_form)}${kv('Participation proposée',`${t.stake_offered_pct} %`)}${kv('Attente du cédant',m(t.seller_asking_price_mfcfa))}${kv('Dette brute / cash',`${m(t.gross_debt_mfcfa)} / ${m(t.cash_mfcfa)}`)}${kv('Dette nette',m(t.net_debt_mfcfa))}${kv('Référence BFR',m(t.working_capital_reference_mfcfa))}${kv('Fenêtre indicative',t.preferred_completion_window)}<div class="source-line">${esc(state.fixture.ui_copy_contract.asking_disclaimer)}</div></section><section class="card"><h2>Profil acquéreur recherché</h2><p style="line-height:1.6;color:#526079">${esc(t.buyer_profile)}</p><div class="notice">${esc(t.funding_expectation)}</div><div class="split-actions" style="margin-top:14px"><button class="btn secondary" data-control-id="EXPRESS_INTEREST">${state.interestRecorded?'Intérêt enregistré ✓':'Manifester mon intérêt'}</button><button class="btn primary" data-control-id="REQUEST_MEETING">${state.meetingRequested?'Réunion demandée ✓':'Demander une réunion management'}</button></div></section></div><section class="card" style="margin-top:18px"><h2>Parcours de transaction</h2><div class="timeline">${t.stages.map(s=>`<div class="stage ${s.status==='DONE'?'done':s.status==='CURRENT'?'current':''}"><span class="stage-dot"></span><label>${esc(s.label)}</label><small>${s.date?esc(s.date):s.status==='CURRENT'?'En cours':'À venir'}</small></div>`).join('')}</div></section><section class="card" style="margin-top:18px"><h2>Principes de processus</h2><ul style="color:#526079;line-height:1.7">${t.terms_notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`}
function risks(){const rs=state.fixture.risk_register;return `<div class="section-title"><div><h2>Risques à diligenter</h2><p>Chaque risque est relié à une preuve, un responsable, une mesure de réduction et une question de diligence.</p></div><span class="pill">${rs.length} risques</span></div><div class="risk-grid">${rs.map(r=>`<article class="risk-card"><div class="risk-head"><div><div class="risk-title">${esc(r.risk_id)} · ${esc(r.title)}</div><div class="risk-meta">${esc(r.category)} · Responsable : ${esc(r.owner)}</div></div><span class="pill ${r.severity==='LOW'?'green':r.severity==='MEDIUM'?'amber':'red'}">${r.severity}</span></div><div class="risk-desc">${esc(r.description)}</div><div><strong style="font-size:12px;color:var(--navy)">Réduction :</strong> <span class="fine">${esc(r.mitigation)}</span></div><div class="risk-foot"><span>Preuves : ${r.evidence.map(d=>`<button class="btn small" data-control-id="OPEN_DOCUMENT" data-document-id="${d}">${d}</button>`).join(' ')}</span><span>${esc(r.status)}</span></div></article>`).join('')}</div>`}
function documents(){const docs=filteredDocs();return `<div class="section-title"><div><h2>Documents</h2><p>Inventaire VDR synthétique avec statut, niveau d’accès, métadonnées et ouverture contrôlée.</p></div><span class="pill green">${state.fixture.documents.length} pièces</span></div><div class="toolbar"><input id="docSearch" class="input" data-control-id="DOCUMENT_SEARCH" placeholder="Rechercher un document" value="${esc(state.docFilter)}"><select id="folderFilter" class="select" data-control-id="DOCUMENT_FOLDER_FILTER"><option value="ALL">Tous les dossiers</option>${state.fixture.vdr.folders.map(f=>`<option value="${esc(f)}">${esc(f)}</option>`).join('')}</select></div><div class="doc-list">${docs.map(d=>`<div class="doc-row"><div><div class="doc-title">${esc(d.title)}</div><div class="doc-sub">${esc(d.document_id)} · ${esc(d.document_type)}</div></div><div class="hide-mobile">${esc(d.folder.replace(/_/g,' '))}</div><div class="hide-mobile status ${d.status}">${esc(d.status)}</div><div class="hide-mobile">${d.pages} p.</div><button class="btn small" data-control-id="OPEN_DOCUMENT" data-document-id="${d.document_id}">Ouvrir</button></div>`).join('')||'<div class="empty">Aucun document ne correspond au filtre.</div>'}</div>`}
function qa(){const all=state.fixture.qa_threads;const qs=state.qaFilter==='ALL'?all:all.filter(q=>q.status===state.qaFilter);return `<div class="section-title"><div><h2>Questions & réponses</h2><p>Fil de diligence documenté, assigné et journalisé. Les pièces liées ouvrent le même viewer documentaire.</p></div><button class="btn primary" data-control-id="ASK_QUESTION">Poser une question</button></div><div class="toolbar"><select id="qaFilter" class="select" data-control-id="QA_STATUS_FILTER"><option value="ALL">Tous les statuts</option>${['OPEN','IN_REVIEW','ANSWERED'].map(x=>`<option ${state.qaFilter===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="qa-list">${qs.map(q=>qaCard(q)).join('')}</div>`}
function qaCard(q){return `<article class="qa-card"><div class="qa-q">${esc(q.qa_id)} · ${esc(q.question)}</div><div class="qa-meta"><span>${esc(q.category)}</span><span>Statut : ${esc(q.status)}</span><span>Assigné : ${esc(q.assigned_to)}</span><span>Pièce : <button class="btn small" data-control-id="OPEN_DOCUMENT" data-document-id="${q.document_id}">${esc(q.document_id)}</button></span></div>${q.answer?`<div class="qa-a"><strong>Réponse</strong><br>${esc(q.answer)}</div>`:'<div class="qa-empty">Réponse en attente dans ce scénario.</div>'}</article>`}
function barChart(){const rows=state.fixture.financials.income_statement,max=Math.max(...state.fixture.financials.income_statement.map(x=>x.revenue));return `<div class="legend"><span><i style="background:#173e78"></i>Chiffre d’affaires</span><span><i style="background:#2bb169"></i>EBITDA</span></div><div class="bar-chart">${rows.map(x=>`<div class="bar-col"><div class="bar-stack"><div class="bar rev" style="height:${Math.round(x.revenue/max*150)}px" title="CA ${x.revenue}"></div><div class="bar ebitda" style="height:${Math.max(7,Math.round(x.ebitda/max*150))}px" title="EBITDA ${x.ebitda}"></div></div><div class="bar-label">${x.year}</div><div class="bar-label"><b>${fmt.format(x.revenue)}</b> / ${fmt.format(x.ebitda)}</div></div>`).join('')}</div>`}
function incomeTable(){const rows=state.fixture.financials.income_statement;const fields=[['revenue','Chiffre d’affaires'],['cogs','Coût des ventes'],['gross_profit','Marge brute'],['ebitda','EBITDA'],['da','Dotations'],['ebit','EBIT'],['interest','Intérêts'],['ebt','Résultat avant impôt'],['tax','Impôt'],['net_income','Résultat net']];return table(rows,fields)}
function balanceTable(){const rows=state.fixture.financials.balance_sheet;const fields=[['cash','Trésorerie'],['receivables','Créances'],['inventory','Stocks'],['ppe','Immobilisations'],['total_assets','Total actif'],['debt','Dette brute'],['payables','Fournisseurs'],['equity','Capitaux propres'],['net_debt','Dette nette'],['working_capital','BFR'],['dso_days','DSO (jours)'],['inventory_days','Stock (jours)'],['dpo_days','DPO (jours)']];return table(rows,fields)}
function cashTable(){const rows=state.fixture.financials.cash_flow;const fields=[['ebitda','EBITDA'],['cash_tax','Impôt cash'],['interest','Intérêts'],['change_nwc','Variation BFR'],['capex','Capex'],['free_cash_flow','Flux de trésorerie disponible']];return table(rows,fields)}
function table(rows,fields){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Indicateur</th>${rows.map(r=>`<th>${r.year}</th>`).join('')}</tr></thead><tbody>${fields.map(([k,l])=>`<tr><td class="${['revenue','ebitda','net_income','total_assets','net_debt','free_cash_flow'].includes(k)?'emph':''}">${esc(l)}</td>${rows.map(r=>`<td>${r[k]==null?'—':typeof r[k]==='number'?(Number.isInteger(r[k])?fmt.format(r[k]):r[k].toFixed(1).replace('.',',')):esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function kv(a,b){return `<div class="kv"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`}
function filteredDocs(){const q=state.docFilter.toLowerCase();return state.fixture.documents.filter(d=>!q||(`${d.title} ${d.document_id} ${d.folder} ${d.document_type}`).toLowerCase().includes(q))}
function bindTab(){
  $$('[data-control-id]', $('#tabSlot')).forEach(el=>el.addEventListener('click',()=>handleControl(el.dataset.controlId,{documentId:el.dataset.documentId})));
  $('#docSearch')?.addEventListener('input',e=>{audit('FILTER_APPLIED',{control_id:'DOCUMENT_SEARCH'});state.docFilter=e.target.value;const pos=e.target.selectionStart;renderTab();const n=$('#docSearch');n.focus();n.setSelectionRange(pos,pos)});
  $('#folderFilter')?.addEventListener('change',e=>{audit('FILTER_APPLIED',{control_id:'DOCUMENT_FOLDER_FILTER'});state.docFilter=e.target.value==='ALL'?'':e.target.value;renderTab()});
  $('#qaFilter')?.addEventListener('change',e=>{audit('FILTER_APPLIED',{control_id:'QA_STATUS_FILTER'});state.qaFilter=e.target.value;renderTab()});
}
async function openDocument(id){
  const d=state.fixture.documents.find(x=>x.document_id===id); if(!d){toast('Document introuvable',id,'error');return}
  if(!allowed('AUTHORIZED')){showGate('OPEN_DOCUMENT');return}
  audit('DOCUMENT_VIEWED',{document_id:id}); state.selectedDoc=d; if(d.content){state.docContent=d.content}else{try{state.docContent=await fetch('./'+d.file_path).then(r=>r.text())}catch{state.docContent=d.summary}}
  state.modal={kind:'document',doc:d};renderModal();
}
function attemptDownload(id){const d=state.fixture.documents.find(x=>x.document_id===id);audit('DOWNLOAD_ATTEMPT',{document_id:id});if(!d?.download_allowed){toast('Téléchargement bloqué','Le téléchargement est désactivé par défaut pour cette pièce. La consultation reste journalisée dans le viewer.','warning');return}toast('Téléchargement simulé','Aucun fichier réel n’est téléchargé dans la référence.')}
function createQuestion(){state.modal={kind:'ask'};renderModal()}
function submitQuestion(){const el=$('#newQuestion');const txt=el?.value.trim()||'';if(!txt){toast('Question requise','Saisissez une question avant validation.','warning');return}const id=`QA-DEMO-${String(state.fixture.qa_threads.length+1).padStart(3,'0')}`;state.fixture.qa_threads.unshift({qa_id:id,category:'Nouvelle question',document_id:'DOC-FIN-003',question:txt,asked_by:'Acheteur — démo',assigned_to:'Cédant',status:'OPEN',visibility:'ALL_AUTHORIZED',asked_at:new Date().toISOString(),answer:null,attachments:[]});audit('QUESTION_CREATED',{qa_id:id});state.modal=null;renderModal();toast('Question créée',`${id} a été ajouté au fil de démonstration.`);if(state.tab==='qa')renderTab()}
function renderModal(){const slot=$('#modalSlot');if(!state.modal){slot.innerHTML='';return}const md=state.modal;if(md.kind==='gate'){slot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(md.title)}</h2><button class="closex" aria-label="Fermer" data-control-id="MODAL_CLOSE">×</button></div><div class="modal-body"><div class="notice warning"><strong>${esc(md.code)}</strong><br>${esc(md.message)}</div><p class="fine" style="margin-top:14px">Dans l’application de production, le contrôle d’autorisation doit être appliqué côté serveur. Ce modal n’est qu’une simulation de référence.</p></div><div class="modal-foot"><button class="btn closebtn" data-control-id="MODAL_CLOSE">Fermer</button></div></div></div>`}
  if(md.kind==='scope'){slot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(md.title)}</h2><button class="closex" data-control-id="MODAL_CLOSE">×</button></div><div class="modal-body"><div class="notice">${esc(md.message)}</div><p class="fine">Dans la plateforme cible, cette action doit router vers la surface indiquée par l’Interaction Registry.</p></div><div class="modal-foot"><button class="btn closebtn" data-control-id="MODAL_CLOSE">Fermer</button></div></div></div>`}
  if(md.kind==='document'){const d=md.doc;slot.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(930px,100%)"><div class="modal-head"><h2>${esc(d.title)}</h2><button class="closex" aria-label="Fermer" data-control-id="MODAL_CLOSE">×</button></div><div class="modal-body"><div class="grid two"><div><div class="notice"><strong>Viewer documentaire synthétique</strong><br>Filigrane requis · téléchargement ${d.download_allowed?'autorisé':'désactivé'} · ouverture journalisée.</div><pre style="white-space:pre-wrap;line-height:1.55;color:#47566e;background:#f8fafc;border:1px solid var(--line);border-radius:9px;padding:14px;max-height:430px;overflow:auto">${esc(state.docContent)}</pre></div><div class="card" style="box-shadow:none"><h3>Métadonnées</h3>${kv('Référence',d.document_id)}${kv('Dossier',d.folder)}${kv('Statut',d.status)}${kv('Date',d.date)}${kv('Version',d.version)}${kv('Pages',d.pages)}${kv('Accès',d.tier)}${kv('Téléchargement',d.download_allowed?'Oui':'Non')}</div></div></div><div class="modal-foot"><button class="btn" data-control-id="DOWNLOAD_DOCUMENT" data-document-id="${d.document_id}">Télécharger</button><button class="btn closebtn" data-control-id="MODAL_CLOSE">Fermer</button></div></div></div>`}
  if(md.kind==='ask'){slot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>Poser une question de diligence</h2><button class="closex" data-control-id="MODAL_CLOSE">×</button></div><div class="modal-body"><label class="fine" for="newQuestion">Question</label><textarea id="newQuestion" data-control-id="QUESTION_TEXT_INPUT" class="textarea" rows="5" style="width:100%;margin-top:6px" placeholder="Ex. Pouvez-vous documenter le renouvellement du contrat client principal ?"></textarea><p class="fine">Ce formulaire crée uniquement un état local de démonstration. En production : attribution, visibilité, pièce liée et audit sont obligatoires.</p></div><div class="modal-foot"><button class="btn closebtn" data-control-id="MODAL_CLOSE">Annuler</button><button class="btn primary" id="submitQuestion" data-control-id="QUESTION_SUBMIT">Créer la question</button></div></div></div>`}
  $$('[data-control-id]',slot).forEach(el=>el.addEventListener('click',()=>handleControl(el.dataset.controlId,{documentId:el.dataset.documentId})));
  $('#newQuestion',slot)?.addEventListener('input',e=>audit('QUESTION_TEXT_CHANGED',{control_id:'QUESTION_TEXT_INPUT',length:e.target.value.length}));
}
function renderVdr(){
  const f=state.fixture; document.querySelector('#app').innerHTML=`<div class="vdr-shell"><div class="vdr-top"><button class="back-vdr" id="backVdr" data-control-id="VDR_BACK">← Dossier</button><img class="logo-mini" src="./assets/dealpme-logo.jpg" alt="DealPME"><div class="sep"></div><div class="vdr-title"><strong>${esc(f.case_id)} · ${esc(f.master.company)}</strong><small>VDR synthétique · accès autorisé · ${f.documents.length} documents · téléchargement désactivé par défaut</small></div><span class="pill green">Session T2</span></div><div class="vdr-grid"><aside class="folder-pane"><input id="vdrSearch" class="input vdr-search" data-control-id="VDR_SEARCH" placeholder="Rechercher"><h3 style="color:var(--navy);font-size:13px">Dossiers</h3>${f.vdr.folders.map(folder=>`<button class="folder-item ${state.selectedFolder===folder?'active':''}" data-control-id="VDR_SELECT_FOLDER" data-folder="${esc(folder)}"><span>${esc(folder.replace(/^\d+_/,'').replace(/_/g,' '))}</span><b>${f.documents.filter(d=>d.folder===folder).length}</b></button>`).join('')}<div class="security-note">${esc(f.ui_copy_contract.vdr_protection_copy)}</div></aside><section class="doc-pane"><div id="vdrDocList"></div></section><aside class="detail-pane"><div id="vdrDetail"></div></aside></div></div><div class="toast-host"></div><div id="modalSlot"></div>`;
  $('#backVdr').addEventListener('click',()=>handleControl('VDR_BACK')); $$('.folder-item').forEach(b=>b.addEventListener('click',()=>handleControl('VDR_SELECT_FOLDER',{folder:b.dataset.folder}))); $('#vdrSearch').addEventListener('input',()=>{audit('FILTER_APPLIED',{control_id:'VDR_SEARCH'});renderVdrDocList()}); renderVdrDocList();
}
function renderVdrDocList(){const q=$('#vdrSearch')?.value.toLowerCase()||'';let docs=state.fixture.documents.filter(d=>d.folder===state.selectedFolder);if(q)docs=state.fixture.documents.filter(d=>(d.title+d.document_id+d.folder).toLowerCase().includes(q));const host=$('#vdrDocList');host.innerHTML=`<div class="section-title"><div><h2>${esc(state.selectedFolder.replace(/^\d+_/,'').replace(/_/g,' '))}</h2><p>${docs.length} document(s) · consultation journalisée</p></div></div>${docs.map(d=>`<div class="vdr-doc ${state.selectedDoc?.document_id===d.document_id?'active':''}"><button data-control-id="VDR_SELECT_DOCUMENT" data-vdr-doc="${d.document_id}"><div class="doc-title">${esc(d.title)}</div><div class="doc-sub">${esc(d.document_id)} · ${esc(d.status)} · ${d.pages} p.</div></button><span class="pill">${d.download_allowed?'DL autorisé':'Lecture seule'}</span></div>`).join('')||'<div class="empty">Aucun document.</div>'}`;$$('[data-vdr-doc]').forEach(b=>b.addEventListener('click',()=>handleControl('VDR_SELECT_DOCUMENT',{documentId:b.dataset.vdrDoc})));if(!state.selectedDoc && docs[0])selectVdrDoc(docs[0].document_id,false)}
async function selectVdrDoc(id,rerender=true){const d=state.fixture.documents.find(x=>x.document_id===id);state.selectedDoc=d;state.docContent=d.content||await fetch('./'+d.file_path).then(r=>r.text()).catch(()=>d.summary);audit('DOCUMENT_VIEWED',{document_id:id,surface:'VDR'});if(rerender)renderVdrDocList();const qa=state.fixture.qa_threads.filter(q=>q.document_id===id);$('#vdrDetail').innerHTML=`<div class="viewer"><div class="viewer-watermark">DEALPME · ${state.profile} · ${state.fixture.case_id} · SYNTHÉTIQUE</div><div class="viewer-content">${esc(state.docContent)}</div></div><div class="doc-meta-list" style="margin-top:14px">${kv('Référence',d.document_id)}${kv('Date',d.date)}${kv('Statut',d.status)}${kv('Téléchargement',d.download_allowed?'Autorisé':'Désactivé')}<div class="split-actions" style="margin-top:10px"><button class="btn small" id="vdrDownload" data-control-id="DOWNLOAD_DOCUMENT">Télécharger</button><button class="btn small primary" id="vdrAsk" data-control-id="ASK_QUESTION">Poser une question</button></div></div><div class="vdr-qa"><h3 style="color:var(--navy)">Q&R liées (${qa.length})</h3>${qa.slice(0,3).map(qaCard).join('')||'<div class="qa-empty">Aucune question liée.</div>'}</div>`;$('#vdrDownload').addEventListener('click',()=>handleControl('DOWNLOAD_DOCUMENT',{documentId:id}));$('#vdrAsk').addEventListener('click',()=>handleControl('ASK_QUESTION'));$$('[data-control-id="OPEN_DOCUMENT"]',$('#vdrDetail')).forEach(b=>b.addEventListener('click',()=>openDocument(b.dataset.documentId)))}
window.addEventListener('hashchange',()=>{const h=(location.hash||'#overview').slice(1);if(h==='vdr')openVdr(true);else if(['overview','financials','transaction','risks','documents','qa'].includes(h)){state.tab=h; if($('#tabSlot')){renderTabs();renderTab()}}});
load().catch(err=>{document.querySelector('#app').innerHTML=`<div style="padding:40px;font-family:Arial"><h1>Erreur de chargement</h1><pre>${esc(err.stack||err)}</pre></div>`});
