import { Panel, StateBanner } from "@dealpme/ui";
import { api } from "../../../../lib/api";
import { requireRole } from "../../../../lib/guards";
import type { ManagedEvent } from "../../../../lib/events";
import { AccountBrandForm } from "./brand-form";
export const metadata = { title: "Intégration Remo" };
export default async function Integration() {
  const { token } = await requireRole("CCI_OFFICER", "PLATFORM_ADMIN");
  const data = await api<{ provider: string; accountKey: string; companyId: string | null; concurrentLimit: number; quotaReference: string; branding: ManagedEvent["branding"]; brandRevision: number; canEditDefaults: boolean; ssoEnabled: boolean; saml: Record<string, string> | null }>("/events/integration", { token });
  return <div className="dp-stack"><a href="/organisateur/evenements">← Événements</a><h1>Intégration Remo</h1><Panel title="Compte et capacités"><dl className="dp-deflist"><dt>Fournisseur</dt><dd>{data.provider}</dd><dt>Compte partagé</dt><dd>{data.accountKey}</dd><dt>Company ID</dt><dd>{data.companyId ?? "Non configuré"}</dd><dt>Simultanéité configurée</dt><dd>{data.concurrentLimit} · {data.quotaReference}</dd></dl><p>Pilotage depuis DealPME : création, personnalisation, invitations, présences, associations aux groupes existants et suppression distante explicite.</p><StateBanner tone="info" title="Initialisation du compte fournisseur">Le Swagger ne décrit pas de réglage du SSO, du domaine, du favicon ou des emails globaux. Leur activation initiale se fait chez Remo ; les parcours métier restent dans DealPME.</StateBanner></Panel><Panel title="Branding général et héritage"><AccountBrandForm branding={data.branding} revision={data.brandRevision} editable={data.canEditDefaults}/></Panel><Panel title="SSO SAML"><p>{data.ssoEnabled ? "IdP DealPME configuré : assertions signées RSA-SHA256, email vérifié, demandes à usage unique." : "SSO non activé : renseigner les métadonnées et certificats côté serveur."}</p>{data.saml ? <><dl className="dp-deflist">{Object.entries(data.saml).map(([key,value])=><div key={key}><dt>{key}</dt><dd style={{overflowWrap:"anywhere"}}>{value}</dd></div>)}</dl><a href="/sso/remo/metadata" className="dp-btn dp-btn-secondary" data-control-id="REMO_SAML_METADATA">Consulter les métadonnées publiques SAML</a></> : null}<p>Le SSO est commun au compte Remo et authentifie l&apos;utilisateur. L&apos;invitation à la salle reste nécessaire. Les sessions Remo déjà ouvertes suivent la politique du fournisseur.</p></Panel><Panel title="Raccordement et qualification"><p>Swagger public : <a href="https://api.virtual.events.com/api/docs/" target="_blank" rel="noreferrer">documentation officielle (nouvel onglet)</a>.</p><p>Les clés API et de signature ne sont jamais renvoyées à cette page. La recette du compte réel reste nécessaire pour les droits, les quotas, le SSO et le rendu des visuels.</p></Panel></div>;
}
