"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button,Checkbox,Field,Input,StateBanner } from "@dealpme/ui";
export function AppointmentForm(){
  const router=useRouter(),[slot,setSlot]=useState(""),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[done,setDone]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError(null);setDone(false);try{const r=await fetch("/api/diaspora",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestedSlot:`${slot}:00Z`,crossBorderNoticeAcknowledged:ack})});const d=await r.json() as {ok:boolean;message?:string};if(!d.ok){setError(d.message??"Demande impossible");return;}setDone(true);router.refresh();}catch{setError("Connexion interrompue. Actualisez vos demandes avant de recommencer.");}finally{setBusy(false);}}
  return <form className="dp-stack" onSubmit={submit}>{error?<StateBanner tone="danger" title="Demande non confirmée" controlId="DIA_ERROR">{error}</StateBanner>:null}{done?<StateBanner tone="success" title="Demande enregistrée">Un officier doit confirmer le créneau avant l'accès à l'entretien.</StateBanner>:null}<Field id="appointment-slot" label="Créneau souhaité — heure du Togo (UTC)"><Input id="appointment-slot" data-control-id="DIA_SLOT" type="datetime-local" required value={slot} onChange={e=>setSlot(e.target.value)}/></Field><StateBanner tone="info" title="Avis transfrontalier">Les transferts, le change et les obligations fiscales dépendent de votre situation et des pays concernés. Faites vérifier ces points par votre banque et vos conseils. Cet entretien ne vaut pas validation réglementaire ni conseil de change.</StateBanner><Checkbox id="cross-border" data-control-id="DIA_NOTICE" label="J'ai pris connaissance de cet avis transfrontalier." checked={ack} onChange={e=>setAck(e.target.checked)}/><Button type="submit" controlId="DIA_REQUEST" disabled={!ack||busy} state={busy?"loading":"default"}>Demander un entretien de 30 minutes</Button></form>;
}
